# Generated by Django 4.2 on 2025-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Responder', 'Responder'), ('Admin', 'Admin')], default='Citizen', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
