# Generated by Django 4.2 on 2025-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherlog_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlog',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
