# Generated by Django 4.2 on 2025-05-30 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherlog_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlog',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
