# Generated by Django 4.2 on 2025-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_warehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
