# Generated by Django 4.2 on 2025-10-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_assigned_responder'),
        ('resources', '0003_inventory_batch_id_inventory_source_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedeployment',
            name='incident',
            field=models.ForeignKey(blank=True, help_text='Incident this resource was deployed for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='incidents.incident'),
        ),
    ]
