# Generated by Django 4.2 on 2025-10-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_updated_at_resourceunit_assigned_incident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
