# Generated by Django 4.2 on 2025-10-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resourcerequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Inbound / Stock Add'), ('out', 'Outbound / Deployment'), ('return', 'Returned Stock'), ('adjustment', 'Manual Adjustment')], default='in', max_length=15),
        ),
        migrations.AlterField(
            model_name='resource',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='Initial or baseline stock count.'),
        ),
    ]
