# Generated by Django 4.2 on 2025-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
