# Generated by Django 4.2 on 2025-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_locationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheltertype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
