# Generated by Django 4.2 on 2025-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_sheltertype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
