# Generated by Django 4.2 on 2025-05-29 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('resource_shortage', 'Resource Shortage')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, help_text='Optional version tag (e.g. v1.0, beta)', max_length=20)),
            ],
            options={
                'verbose_name': 'Forecast Model',
                'verbose_name_plural': 'Forecast Models',
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='The date the forecast applies to')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('affected_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('area_name', models.CharField(blank=True, help_text='Optional name for the affected area', max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('confidence', models.FloatField(help_text='Confidence level from 0 (low) to 1 (high)')),
                ('details', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasting.forecastmodel')),
            ],
            options={
                'verbose_name': 'Forecast Result',
                'verbose_name_plural': 'Forecast Results',
                'ordering': ['-forecast_date', '-predicted_at'],
            },
        ),
    ]
