# Generated by Django 4.2 on 2025-05-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodel',
            name='model_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('resource_shortage', 'Resource Shortage'), ('heat_wave', 'Heat Wave')], max_length=20),
        ),
    ]
